import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateInitialSchema1786325855482 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto`);

    // ============================================================
    // TABLA: User
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "User" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "UserName" varchar(100) NOT NULL UNIQUE,
        "Email" varchar(200) NULL UNIQUE,
        "FirstName" varchar(100) NOT NULL,
        "LastName" varchar(100) NOT NULL,
        "PasswordHash" bytea NOT NULL,
        "PasswordSalt" bytea NOT NULL,
        "LastLoginAt" timestamp(6) NULL,
        "FailedLoginAttempts" integer NOT NULL DEFAULT 0,
        "LockoutEnd" timestamp(6) NULL,
        "PasswordChangedAt" timestamp(6) NULL,
        "TwoFactorEnabled" boolean NOT NULL DEFAULT false,
        "TwoFactorSecret" varchar(255) NULL,
        "SecurityStamp" uuid NOT NULL DEFAULT gen_random_uuid(),
        "State" boolean NOT NULL DEFAULT true,
        "Photo" varchar(250) NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_User_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_User_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_User_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_User_UserName" ON "User" ("UserName") INCLUDE ("Email")`,
    );

    // ============================================================
    // TABLA: Audit
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "Audit" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "UserId" integer NULL,
        "Type" varchar(50) NOT NULL,
        "TableName" varchar(100) NOT NULL,
        "DateTime" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "OldValues" text NULL,
        "NewValues" text NULL,
        "PrimaryKey" varchar(100) NOT NULL,
        "AffectedColumns" text NULL,
        CONSTRAINT "FK_Audit_User" FOREIGN KEY ("UserId")
          REFERENCES "User" ("Id") ON DELETE SET NULL
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_Audit_UserId" ON "Audit" ("UserId")`,
    );

    // ============================================================
    // TABLA: Menu
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "Menu" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "ParentMenuId" integer NULL,
        "Code" varchar(50) NOT NULL,
        "Name" varchar(100) NOT NULL,
        "Url" varchar(200) NULL,
        "DisplayOrder" integer NOT NULL DEFAULT 0,
        "State" boolean NOT NULL DEFAULT true,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_Menu_Parent" FOREIGN KEY ("ParentMenuId")
          REFERENCES "Menu" ("Id")
          ON DELETE NO ACTION
          ON UPDATE NO ACTION,
        CONSTRAINT "CK_Menu_NoSelfReference" CHECK ("Id" <> "ParentMenuId"),
        CONSTRAINT "FK_Menu_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_Menu_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_Menu_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_Menu_ParentMenuId" ON "Menu" ("ParentMenuId")`,
    );
    await queryRunner.query(`CREATE INDEX "IX_Menu_Name" ON "Menu" ("Name")`);
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_Menu_Code" ON "Menu" ("Code") WHERE "DeletedAt" IS NULL`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_Menu_Url" ON "Menu" ("Url") WHERE "DeletedAt" IS NULL`,
    );

    // ============================================================
    // TABLA: Permission
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "Permission" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "MenuId" integer NULL,
        "Code" varchar(50) NOT NULL UNIQUE,
        "Name" varchar(100) NOT NULL,
        "Description" varchar(300) NULL,
        "State" boolean NOT NULL DEFAULT true,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_Permission_Menu" FOREIGN KEY ("MenuId")
          REFERENCES "Menu" ("Id")
          ON DELETE SET NULL,
        CONSTRAINT "FK_Permission_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_Permission_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_Permission_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_Permission_MenuId" ON "Permission" ("MenuId")`,
    );

    // ============================================================
    // TABLA: Role
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "Role" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "Code" varchar(50) NOT NULL UNIQUE,
        "Name" varchar(100) NOT NULL UNIQUE,
        "Description" varchar(500) NULL,
        "State" boolean NOT NULL DEFAULT true,
        "IsSystemRole" boolean NOT NULL DEFAULT false,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_Role_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_Role_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_Role_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);

    // ============================================================
    // TABLA: RoleMenu
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "RoleMenu" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "RoleId" integer NOT NULL,
        "MenuId" integer NOT NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_RoleMenu_Role" FOREIGN KEY ("RoleId")
          REFERENCES "Role" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RoleMenu_Menu" FOREIGN KEY ("MenuId")
          REFERENCES "Menu" ("Id") ON DELETE CASCADE,
        CONSTRAINT "UQ_RoleMenu" UNIQUE ("RoleId", "MenuId"),
        CONSTRAINT "FK_RoleMenu_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_RoleMenu_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_RoleMenu_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_RoleMenu_RoleId" ON "RoleMenu" ("RoleId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IX_RoleMenu_MenuId" ON "RoleMenu" ("MenuId")`,
    );

    // ============================================================
    // TABLA: RolePermission
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "RolePermission" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "RoleId" integer NOT NULL,
        "PermissionId" integer NOT NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_RolePermission_Role" FOREIGN KEY ("RoleId")
          REFERENCES "Role" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RolePermission_Permission" FOREIGN KEY ("PermissionId")
          REFERENCES "Permission" ("Id") ON DELETE CASCADE,
        CONSTRAINT "UQ_RolePermission" UNIQUE ("RoleId", "PermissionId"),
        CONSTRAINT "FK_RolePermission_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_RolePermission_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_RolePermission_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_RolePermission_RoleId" ON "RolePermission" ("RoleId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IX_RolePermission_PermissionId" ON "RolePermission" ("PermissionId")`,
    );

    // ============================================================
    // TABLA: UserRole
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "UserRole" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "UserId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_UserRole_User" FOREIGN KEY ("UserId")
          REFERENCES "User" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRole_Role" FOREIGN KEY ("RoleId")
          REFERENCES "Role" ("Id") ON DELETE CASCADE,
        CONSTRAINT "UQ_UserRole" UNIQUE ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRole_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_UserRole_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_UserRole_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_UserRole_UserId" ON "UserRole" ("UserId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IX_UserRole_RoleId" ON "UserRole" ("RoleId")`,
    );

    // ============================================================
    // AUDITORÍA DE AUTORIZACIÓN (OWASP A09: Security Logging Failures)
    // Cada alta/baja/cambio de rol de un usuario o de permiso de un rol
    // queda registrado en "Audit" automáticamente, sin depender de que
    // cada endpoint de administración recuerde loguearlo a mano.
    // ============================================================
    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION audit_authorization_change()
      RETURNS trigger
      LANGUAGE plpgsql
      AS $$
      BEGIN
        IF TG_OP = 'DELETE' THEN
          INSERT INTO "Audit" ("UserId","Type","TableName","PrimaryKey","OldValues")
          VALUES (COALESCE(OLD."UpdatedById", OLD."CreatedById"), 'DELETE', TG_TABLE_NAME, OLD."Id"::text, row_to_json(OLD)::text);
          RETURN OLD;
        ELSIF TG_OP = 'UPDATE' THEN
          INSERT INTO "Audit" ("UserId","Type","TableName","PrimaryKey","OldValues","NewValues")
          VALUES (COALESCE(NEW."UpdatedById", NEW."CreatedById"), 'UPDATE', TG_TABLE_NAME, NEW."Id"::text, row_to_json(OLD)::text, row_to_json(NEW)::text);
          RETURN NEW;
        ELSE
          INSERT INTO "Audit" ("UserId","Type","TableName","PrimaryKey","NewValues")
          VALUES (NEW."CreatedById", 'INSERT', TG_TABLE_NAME, NEW."Id"::text, row_to_json(NEW)::text);
          RETURN NEW;
        END IF;
      END;
      $$
    `);

    for (const table of ['UserRole', 'RolePermission']) {
      await queryRunner.query(`
        CREATE TRIGGER "TR_${table}_Audit"
        AFTER INSERT OR UPDATE OR DELETE ON "${table}"
        FOR EACH ROW EXECUTE FUNCTION audit_authorization_change()
      `);
    }

    // ============================================================
    // TABLA: UserLoginHistory
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "UserLoginHistory" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "UserId" integer NOT NULL,
        "LoginAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "IpAddress" varchar(45) NULL,
        "UserAgent" varchar(255) NULL,
        "Success" boolean NOT NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_UserLoginHistory_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_UserLoginHistory_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);

    // ============================================================
    // TABLA: UserPasswordHistory
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "UserPasswordHistory" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "UserId" integer NOT NULL,
        "PasswordHash" bytea NOT NULL,
        "PasswordSalt" bytea NOT NULL,
        "ChangedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_UserPasswordHistory_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_UserPasswordHistory_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_UserPasswordHistory_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_UserPasswordHistory_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_UserPasswordHistory_UserId" ON "UserPasswordHistory" ("UserId")`,
    );

    // ============================================================
    // TABLA: UserSession
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "UserSession" (
        "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        "UserId" integer NOT NULL,
        "Token" varchar(500) NOT NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "ExpiresAt" timestamp(6) NOT NULL,
        "RevokedAt" timestamp(6) NULL,
        "IpAddress" varchar(45) NULL,
        "UserAgent" varchar(255) NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_UserSession_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_UserSession_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_UserSession_UserId" ON "UserSession" ("UserId")`,
    );

    // ============================================================
    // TABLA: UserMFADevices
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "UserMFADevices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "UserId" integer NOT NULL,
        "DeviceName" varchar(100) NOT NULL,
        "Secret" varchar(255) NOT NULL,
        "IsTrusted" boolean NOT NULL DEFAULT false,
        "RegisteredAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "LastUsedAt" timestamp(6) NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_UserMFADevices_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_UserMFADevices_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_UserMFADevices_UserId" ON "UserMFADevices" ("UserId")`,
    );

    // ============================================================
    // ROW VERSION
    // SQL Server ROWVERSION no existe en PostgreSQL: se reemplaza por
    // BIGINT incrementado en cada UPDATE vía trigger. "Audit" queda fuera
    // a propósito: es un log de solo-inserción y no tiene columna
    // RowVersion.
    // ============================================================
    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION set_row_version()
      RETURNS trigger
      LANGUAGE plpgsql
      AS $$
      BEGIN
        NEW."RowVersion" = OLD."RowVersion" + 1;
        RETURN NEW;
      END;
      $$
    `);

    const tablesWithRowVersion = [
      'User',
      'Menu',
      'Permission',
      'Role',
      'RoleMenu',
      'RolePermission',
      'UserRole',
      'UserLoginHistory',
      'UserPasswordHistory',
      'UserSession',
      'UserMFADevices',
    ];
    for (const table of tablesWithRowVersion) {
      await queryRunner.query(`
        CREATE TRIGGER "TR_${table}_RowVersion"
        BEFORE UPDATE ON "${table}"
        FOR EACH ROW EXECUTE FUNCTION set_row_version()
      `);
    }

    // ============================================================
    // RESOLUCIÓN DE PERMISOS Y MENÚ EFECTIVOS (multi-rol)
    //
    // Un usuario puede tener varios roles; sus permisos reales son la
    // UNIÓN (no la intersección) de los permisos de todos sus roles
    // activos. Este es el modelo de autorización: solo concede (no hay
    // "deny" explícito), y por defecto niega — un usuario sin roles, o
    // cuyo rol/permiso fue desactivado (State = false) o dado de baja
    // (DeletedAt), pierde el acceso de inmediato sin tener que borrar
    // filas de RolePermission una por una (fail-closed, OWASP A04).
    //
    // Estas vistas son la ÚNICA fuente que debe consultar la app para
    // autorizar (ej. un guard de NestJS haciendo
    // SELECT 1 FROM "UserPermission" WHERE "UserId"=$1 AND "PermissionCode"=$2).
    // Si cada guard reimplementa el join a mano, es cuestión de tiempo
    // que alguno se olvide de filtrar un rol desactivado o de unir todos
    // los roles del usuario (OWASP A01: Broken Access Control).
    // ============================================================
    await queryRunner.query(`
      CREATE VIEW "UserPermission" AS
      SELECT DISTINCT
        u."Id"   AS "UserId",
        p."Id"   AS "PermissionId",
        p."Code" AS "PermissionCode"
      FROM "User" u
      JOIN "UserRole" ur
        ON ur."UserId" = u."Id"
       AND ur."DeletedAt" IS NULL
      JOIN "Role" r
        ON r."Id" = ur."RoleId"
       AND r."State" = true
       AND r."DeletedAt" IS NULL
      JOIN "RolePermission" rp
        ON rp."RoleId" = r."Id"
       AND rp."DeletedAt" IS NULL
      JOIN "Permission" p
        ON p."Id" = rp."PermissionId"
       AND p."State" = true
       AND p."DeletedAt" IS NULL
      WHERE u."State" = true
        AND u."DeletedAt" IS NULL
    `);

    await queryRunner.query(`
      CREATE VIEW "UserMenu" AS
      SELECT DISTINCT
        u."Id" AS "UserId",
        m."Id" AS "MenuId"
      FROM "User" u
      JOIN "UserRole" ur
        ON ur."UserId" = u."Id"
       AND ur."DeletedAt" IS NULL
      JOIN "Role" r
        ON r."Id" = ur."RoleId"
       AND r."State" = true
       AND r."DeletedAt" IS NULL
      JOIN "RoleMenu" rm
        ON rm."RoleId" = r."Id"
       AND rm."DeletedAt" IS NULL
      JOIN "Menu" m
        ON m."Id" = rm."MenuId"
       AND m."State" = true
       AND m."DeletedAt" IS NULL
      WHERE u."State" = true
        AND u."DeletedAt" IS NULL
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP VIEW "UserMenu"`);
    await queryRunner.query(`DROP VIEW "UserPermission"`);
    await queryRunner.query(`DROP TABLE "UserMFADevices"`);
    await queryRunner.query(`DROP TABLE "UserSession"`);
    await queryRunner.query(`DROP TABLE "UserPasswordHistory"`);
    await queryRunner.query(`DROP TABLE "UserLoginHistory"`);
    await queryRunner.query(`DROP TABLE "UserRole"`);
    await queryRunner.query(`DROP TABLE "RolePermission"`);
    await queryRunner.query(`DROP TABLE "RoleMenu"`);
    await queryRunner.query(`DROP TABLE "Role"`);
    await queryRunner.query(`DROP TABLE "Permission"`);
    await queryRunner.query(`DROP TABLE "Menu"`);
    await queryRunner.query(`DROP TABLE "Audit"`);
    await queryRunner.query(`DROP TABLE "User"`);
    await queryRunner.query(`DROP FUNCTION IF EXISTS set_row_version`);
    await queryRunner.query(
      `DROP FUNCTION IF EXISTS audit_authorization_change`,
    );
  }
}
