import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Tres piezas nuevas de la ficha del paciente:
 *
 * 1. "ReferralReview" — qué dijo el destino (posta/hospital) sobre la
 *    historia clínica que se le mandó: aceptó, rechazó, u observó (con un
 *    PDF de vuelta). 1:1 con Patient, "PENDIENTE" = la fila no existe
 *    (mismo criterio que CounterReferral). El área de Referencias es
 *    quien la registra — permiso nuevo, "REFERRAL_REVIEW_MANAGE".
 * 2. "PatientAttachment" — "Exámenes y documentos": imágenes/PDF/Word/
 *    video sueltos del caso, muchos por paciente (a diferencia de los 1:1
 *    de arriba).
 * 3. Columnas nuevas en "TransitionSummary" para "Subir el documento":
 *    el archivo original, cuando el borrador no se generó (IA o
 *    plantilla) sino que se subió ya redactado.
 */
export class AddReferralReviewAndAttachments1786325861482 implements MigrationInterface {
  name = 'AddReferralReviewAndAttachments1786325861482';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "TransitionSummary" ADD COLUMN "SourceFileName" varchar(255) NULL
    `);
    await queryRunner.query(`
      ALTER TABLE "TransitionSummary" ADD COLUMN "SourceFileSize" integer NULL
    `);
    await queryRunner.query(`
      ALTER TABLE "TransitionSummary" ADD COLUMN "SourceStoragePath" varchar(500) NULL
    `);

    await queryRunner.query(`
      CREATE TABLE "ReferralReview" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "Status" varchar(10) NOT NULL,
        "Notes" varchar(500) NULL,
        "FileName" varchar(255) NULL,
        "FileSize" integer NULL,
        "StoragePath" varchar(500) NULL,
        "ReviewedById" integer NOT NULL,
        "ReviewedAt" timestamp(6) NOT NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "CK_ReferralReview_Status" CHECK ("Status" IN ('ACCEPTED','REJECTED','OBSERVED')),
        CONSTRAINT "FK_ReferralReview_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "UQ_ReferralReview_Patient" UNIQUE ("PatientId"),
        CONSTRAINT "FK_ReferralReview_ReviewedBy" FOREIGN KEY ("ReviewedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_ReferralReview_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_ReferralReview_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_ReferralReview_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "PatientAttachment" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "FileName" varchar(255) NOT NULL,
        "FileSize" integer NOT NULL,
        "StoragePath" varchar(500) NOT NULL,
        "UploadedById" integer NOT NULL,
        "UploadedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_PatientAttachment_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PatientAttachment_UploadedBy" FOREIGN KEY ("UploadedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_PatientAttachment_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_PatientAttachment_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_PatientAttachment_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_PatientAttachment_PatientId" ON "PatientAttachment" ("PatientId")`,
    );

    await queryRunner.query(`
      INSERT INTO "Permission" ("Code","Name","Description","MenuId","CreatedById")
      SELECT 'REFERRAL_REVIEW_MANAGE', 'Registrar respuesta del destino', 'Permite registrar si la posta/hospital aceptó, rechazó u observó la historia clínica de transferencia', NULL, adm."Id"
      FROM (SELECT "Id" FROM "User" WHERE "UserName" = 'admin') AS adm
    `);
    await queryRunner.query(`
      INSERT INTO "RolePermission" ("RoleId","PermissionId","CreatedById")
      SELECT r."Id", p."Id", adm."Id"
      FROM (VALUES ('ADMIN'),('AREA_REFERENCIAS')) AS v("RoleCode")
      JOIN "Role" r ON r."Code" = v."RoleCode"
      CROSS JOIN (SELECT "Id" FROM "Permission" WHERE "Code" = 'REFERRAL_REVIEW_MANAGE') AS p
      CROSS JOIN (SELECT "Id" FROM "User" WHERE "UserName" = 'admin') AS adm
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM "RolePermission" WHERE "PermissionId" = (
        SELECT "Id" FROM "Permission" WHERE "Code" = 'REFERRAL_REVIEW_MANAGE'
      )
    `);
    await queryRunner.query(
      `DELETE FROM "Permission" WHERE "Code" = 'REFERRAL_REVIEW_MANAGE'`,
    );
    await queryRunner.query(`DROP TABLE "PatientAttachment"`);
    await queryRunner.query(`DROP TABLE "ReferralReview"`);
    await queryRunner.query(`
      ALTER TABLE "TransitionSummary" DROP COLUMN "SourceStoragePath"
    `);
    await queryRunner.query(`
      ALTER TABLE "TransitionSummary" DROP COLUMN "SourceFileSize"
    `);
    await queryRunner.query(`
      ALTER TABLE "TransitionSummary" DROP COLUMN "SourceFileName"
    `);
  }
}
