import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Esquema del recorrido pediátrico→adultos que consume iCode-front
 * ("Puente 18+" versión front — ver PUENTE18_FRONTEND_INTEGRATION.md).
 * Dominio nuevo y separado del que ya existe (Patient/LegalGuardian/
 * ClinicalRecord/AccessAuthorization/ClinicalAccessLog, el del requisito
 * oficial IPRESS): comparten "Patient" como sujeto pero ninguna tabla de
 * abajo reemplaza ni se mezcla con las de ese dominio.
 *
 * Se agrega en una migración propia (no se toca CreateInitialSchema) —
 * son 3 ALTER TABLE mínimos sobre columnas de identidad genuina
 * (Patient.Sex, HealthFacility.District, LegalGuardian.HasJourneyAccess)
 * más tablas 100% nuevas.
 */
export class CreateTransitionSchema1786325857482 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // ============================================================
    // ALTER: Patient.Sex — dato de identidad que el mock de transición
    // necesita y el esquema original nunca pidió.
    // ============================================================
    await queryRunner.query(`
      ALTER TABLE "Patient" ADD COLUMN "Sex" varchar(1) NULL
    `);
    await queryRunner.query(`
      ALTER TABLE "Patient" ADD CONSTRAINT "CK_Patient_Sex" CHECK ("Sex" IN ('F','M'))
    `);

    // ============================================================
    // ALTER: HealthFacility.District — para poder reutilizar este mismo
    // catálogo como "posta del distrito" (ver PatientTransition más abajo).
    // ============================================================
    await queryRunner.query(`
      ALTER TABLE "HealthFacility" ADD COLUMN "District" varchar(100) NULL
    `);

    // ============================================================
    // ALTER: LegalGuardian.HasJourneyAccess — el paciente puede
    // revocar/devolver el acceso de su tutor a "Mi recorrido" en
    // cualquier momento, distinto de "IsActive" (que el sistema apaga
    // solo al cumplir 18 — ver TitleTransferService).
    // ============================================================
    await queryRunner.query(`
      ALTER TABLE "LegalGuardian" ADD COLUMN "HasJourneyAccess" boolean NOT NULL DEFAULT true
    `);

    // ============================================================
    // TABLA: MedicalSpecialty
    // Catálogo de especialidades — ver domain/entities/facilities/
    // medical-specialty.entity.ts.
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "MedicalSpecialty" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "Code" varchar(30) NOT NULL UNIQUE,
        "Name" varchar(150) NOT NULL,
        "AdultName" varchar(150) NULL,
        "State" boolean NOT NULL DEFAULT true,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_MedicalSpecialty_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_MedicalSpecialty_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_MedicalSpecialty_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);

    // ============================================================
    // TABLA: HealthFacilityStaffSpecialty
    // Muchos a muchos: un médico puede cubrir más de una especialidad.
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "HealthFacilityStaffSpecialty" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "HealthFacilityStaffId" integer NOT NULL,
        "MedicalSpecialtyId" integer NOT NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_HealthFacilityStaffSpecialty_Staff" FOREIGN KEY ("HealthFacilityStaffId")
          REFERENCES "HealthFacilityStaff" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_HealthFacilityStaffSpecialty_Specialty" FOREIGN KEY ("MedicalSpecialtyId")
          REFERENCES "MedicalSpecialty" ("Id") ON DELETE CASCADE,
        CONSTRAINT "UQ_HealthFacilityStaffSpecialty" UNIQUE ("HealthFacilityStaffId", "MedicalSpecialtyId"),
        CONSTRAINT "FK_HealthFacilityStaffSpecialty_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_HealthFacilityStaffSpecialty_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_HealthFacilityStaffSpecialty_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_HealthFacilityStaffSpecialty_StaffId" ON "HealthFacilityStaffSpecialty" ("HealthFacilityStaffId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IX_HealthFacilityStaffSpecialty_SpecialtyId" ON "HealthFacilityStaffSpecialty" ("MedicalSpecialtyId")`,
    );

    // ============================================================
    // TABLA: PatientTransition
    // Extiende a "Patient" 1:1 con todo lo propio del recorrido —
    // ver domain/entities/patients/patient-transition.entity.ts.
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "PatientTransition" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "State" varchar(30) NOT NULL DEFAULT 'PENDING',
        "MedicalRecordNumber" varchar(30) NOT NULL,
        "PrimaryDiagnosis" varchar(300) NULL,
        "SpecialtyId" integer NOT NULL,
        "AttendingStaffId" integer NULL,
        "District" varchar(100) NULL,
        "HealthPostFacilityId" integer NULL,
        "HealthPostDistanceKm" numeric(6,2) NULL,
        "ReferredToPostAt" timestamp(6) NULL,
        "HospitalReferral" jsonb NULL,
        "Appointment" jsonb NULL,
        "AppointmentAddress" varchar(300) NULL,
        "ArriveMinutesEarly" integer NULL,
        "AdmissionNote" varchar(500) NULL,
        "CounterReferralStatus" varchar(10) NOT NULL DEFAULT 'NONE',
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "CK_PatientTransition_State" CHECK ("State" IN (
          'PENDING','IN_PREPARATION','REFERRED_TO_POST','APPOINTMENT_IN_PROCESS',
          'APPOINTMENT_GRANTED','FIRST_CARE_DONE','LOST_TO_FOLLOW_UP','READMITTED'
        )),
        CONSTRAINT "CK_PatientTransition_CounterReferralStatus" CHECK ("CounterReferralStatus" IN ('NONE','UPLOADED','SENT')),
        CONSTRAINT "FK_PatientTransition_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "UQ_PatientTransition_Patient" UNIQUE ("PatientId"),
        CONSTRAINT "FK_PatientTransition_Specialty" FOREIGN KEY ("SpecialtyId")
          REFERENCES "MedicalSpecialty" ("Id"),
        CONSTRAINT "FK_PatientTransition_AttendingStaff" FOREIGN KEY ("AttendingStaffId")
          REFERENCES "HealthFacilityStaff" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_PatientTransition_HealthPost" FOREIGN KEY ("HealthPostFacilityId")
          REFERENCES "HealthFacility" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_PatientTransition_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_PatientTransition_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_PatientTransition_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_PatientTransition_SpecialtyId" ON "PatientTransition" ("SpecialtyId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IX_PatientTransition_HealthPostFacilityId" ON "PatientTransition" ("HealthPostFacilityId")`,
    );

    // ============================================================
    // TABLA: TransitionSummary
    // La historia clínica de transferencia (borrador IA -> firma) — ver
    // domain/entities/clinical/transition-summary.entity.ts sobre por
    // qué NO se llama "ClinicalSummary".
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "TransitionSummary" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "Status" varchar(10) NOT NULL,
        "Sections" jsonb NOT NULL,
        "PendingChecks" jsonb NULL,
        "DraftedByKind" varchar(10) NOT NULL,
        "DraftedByName" varchar(150) NOT NULL,
        "DraftedAt" timestamp(6) NOT NULL,
        "EditedById" integer NULL,
        "EditedAt" timestamp(6) NULL,
        "ApprovedById" integer NULL,
        "ApprovedAt" timestamp(6) NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "CK_TransitionSummary_Status" CHECK ("Status" IN ('DRAFT','APPROVED')),
        CONSTRAINT "CK_TransitionSummary_DraftedByKind" CHECK ("DraftedByKind" IN ('AI','HUMAN')),
        CONSTRAINT "FK_TransitionSummary_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "UQ_TransitionSummary_Patient" UNIQUE ("PatientId"),
        CONSTRAINT "FK_TransitionSummary_EditedBy" FOREIGN KEY ("EditedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_TransitionSummary_ApprovedBy" FOREIGN KEY ("ApprovedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_TransitionSummary_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_TransitionSummary_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_TransitionSummary_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);

    // ============================================================
    // TABLA: PostNotice
    // Historial de avisos del área a la posta — puede haber más de uno
    // por paciente (aviso "tarde" tras los 18 sigue siendo válido).
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "PostNotice" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "SentAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "SentById" integer NOT NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_PostNotice_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PostNotice_SentBy" FOREIGN KEY ("SentById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_PostNotice_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_PostNotice_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_PostNotice_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_PostNotice_PatientId" ON "PostNotice" ("PatientId")`,
    );

    // ============================================================
    // TABLA: ReferralAlert
    // El especialista reclamándole al área — "Reason" lo recalcula
    // siempre el servidor (ver domain/entities/referrals/referral-alert.entity.ts).
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "ReferralAlert" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "Reason" varchar(20) NOT NULL,
        "SentAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "SentById" integer NOT NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "CK_ReferralAlert_Reason" CHECK ("Reason" IN ('POST_NOTICE','COUNTER_REFERRAL','RESCHEDULE')),
        CONSTRAINT "FK_ReferralAlert_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ReferralAlert_SentBy" FOREIGN KEY ("SentById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_ReferralAlert_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_ReferralAlert_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_ReferralAlert_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_ReferralAlert_PatientId" ON "ReferralAlert" ("PatientId")`,
    );

    // ============================================================
    // TABLA: CounterReferral
    // La carta — 1:1 con Patient. "StoragePath" apunta al volumen de
    // disco local (ver docker-compose y PUENTE18_FRONTEND_INTEGRATION.md).
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "CounterReferral" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "Status" varchar(10) NOT NULL,
        "FileName" varchar(255) NOT NULL,
        "Format" varchar(10) NOT NULL,
        "FileSize" integer NOT NULL,
        "StoragePath" varchar(500) NOT NULL,
        "Code" varchar(50) NULL,
        "UploadedById" integer NOT NULL,
        "UploadedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "SentById" integer NULL,
        "SentAt" timestamp(6) NULL,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "CK_CounterReferral_Status" CHECK ("Status" IN ('UPLOADED','SENT')),
        CONSTRAINT "CK_CounterReferral_Format" CHECK ("Format" IN ('PDF','WORD')),
        CONSTRAINT "FK_CounterReferral_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "UQ_CounterReferral_Patient" UNIQUE ("PatientId"),
        CONSTRAINT "FK_CounterReferral_UploadedBy" FOREIGN KEY ("UploadedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_CounterReferral_SentBy" FOREIGN KEY ("SentById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_CounterReferral_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_CounterReferral_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_CounterReferral_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);

    // ============================================================
    // TABLAS: contenido de "Mi recorrido" (JourneyChecklistItem,
    // JourneyMedication, JourneyAllergy, JourneyContact, JourneyMessage)
    // — todas 1:N con Patient, contenido de cara al paciente, no
    // reutilizan ClinicalRecord (ver domain/entities/journey/*.entity.ts).
    // ============================================================
    await queryRunner.query(`
      CREATE TABLE "JourneyChecklistItem" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "Title" varchar(150) NOT NULL,
        "Detail" varchar(500) NULL,
        "PendingLabel" varchar(150) NULL,
        "Done" boolean NOT NULL DEFAULT false,
        "DisplayOrder" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_JourneyChecklistItem_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JourneyChecklistItem_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyChecklistItem_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyChecklistItem_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_JourneyChecklistItem_PatientId" ON "JourneyChecklistItem" ("PatientId")`,
    );

    await queryRunner.query(`
      CREATE TABLE "JourneyMedication" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "Initial" varchar(10) NULL,
        "Name" varchar(150) NOT NULL,
        "Dose" varchar(100) NULL,
        "Purpose" varchar(300) NULL,
        "DisplayOrder" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_JourneyMedication_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JourneyMedication_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyMedication_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyMedication_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_JourneyMedication_PatientId" ON "JourneyMedication" ("PatientId")`,
    );

    await queryRunner.query(`
      CREATE TABLE "JourneyAllergy" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "Substance" varchar(150) NOT NULL,
        "Detail" varchar(300) NULL,
        "DisplayOrder" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_JourneyAllergy_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JourneyAllergy_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyAllergy_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyAllergy_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_JourneyAllergy_PatientId" ON "JourneyAllergy" ("PatientId")`,
    );

    await queryRunner.query(`
      CREATE TABLE "JourneyContact" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "Role" varchar(100) NOT NULL,
        "Name" varchar(150) NOT NULL,
        "Detail" varchar(300) NULL,
        "DisplayOrder" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_JourneyContact_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JourneyContact_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyContact_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyContact_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_JourneyContact_PatientId" ON "JourneyContact" ("PatientId")`,
    );

    await queryRunner.query(`
      CREATE TABLE "JourneyGuideEntry" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "Question" varchar(300) NOT NULL,
        "Answer" varchar(2000) NOT NULL,
        "DisplayOrder" integer NOT NULL DEFAULT 0,
        "State" boolean NOT NULL DEFAULT true,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_JourneyGuideEntry_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyGuideEntry_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyGuideEntry_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "JourneyMessage" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PatientId" integer NOT NULL,
        "Text" varchar(240) NOT NULL,
        "SentById" integer NOT NULL,
        "SentAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedAt" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "CreatedById" integer NOT NULL,
        "UpdatedAt" timestamp(6) NULL,
        "UpdatedById" integer NULL,
        "DeletedAt" timestamp(6) NULL,
        "DeletedById" integer NULL,
        "RowVersion" bigint NOT NULL DEFAULT 1,
        CONSTRAINT "FK_JourneyMessage_Patient" FOREIGN KEY ("PatientId")
          REFERENCES "Patient" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JourneyMessage_SentBy" FOREIGN KEY ("SentById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyMessage_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyMessage_UpdatedBy" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id"),
        CONSTRAINT "FK_JourneyMessage_DeletedBy" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IX_JourneyMessage_PatientId" ON "JourneyMessage" ("PatientId")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "JourneyMessage"`);
    await queryRunner.query(`DROP TABLE "JourneyGuideEntry"`);
    await queryRunner.query(`DROP TABLE "JourneyContact"`);
    await queryRunner.query(`DROP TABLE "JourneyAllergy"`);
    await queryRunner.query(`DROP TABLE "JourneyMedication"`);
    await queryRunner.query(`DROP TABLE "JourneyChecklistItem"`);
    await queryRunner.query(`DROP TABLE "CounterReferral"`);
    await queryRunner.query(`DROP TABLE "ReferralAlert"`);
    await queryRunner.query(`DROP TABLE "PostNotice"`);
    await queryRunner.query(`DROP TABLE "TransitionSummary"`);
    await queryRunner.query(`DROP TABLE "PatientTransition"`);
    await queryRunner.query(`DROP TABLE "HealthFacilityStaffSpecialty"`);
    await queryRunner.query(`DROP TABLE "MedicalSpecialty"`);
    await queryRunner.query(
      `ALTER TABLE "LegalGuardian" DROP COLUMN "HasJourneyAccess"`,
    );
    await queryRunner.query(
      `ALTER TABLE "HealthFacility" DROP COLUMN "District"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Patient" DROP CONSTRAINT "CK_Patient_Sex"`,
    );
    await queryRunner.query(`ALTER TABLE "Patient" DROP COLUMN "Sex"`);
  }
}
